<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-GKU721D" name="cn.nhsoft.amazoncloud.apitest.positem.PosItemTest1" tests="1" failures="0" timestamp="6 Jun 2020 03:50:31 GMT" time="0.000" errors="1">
  <testcase name="testQuery_feed_1" time="0.000" classname="cn.nhsoft.amazoncloud.apitest.positem.PosItemTest1">
    <error type="java.lang.RuntimeException" message="java.lang.IndexOutOfBoundsException: Index: 3, Size: 3">
      <![CDATA[java.lang.RuntimeException: java.lang.IndexOutOfBoundsException: Index: 3, Size: 3
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:163)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:430)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1274)
	at org.testng.internal.Invoker.createParameters(Invoker.java:989)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1079)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
Caused by: java.lang.IndexOutOfBoundsException: Index: 3, Size: 3
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at org.databene.model.data.ArrayTypeDescriptor.getElement(ArrayTypeDescriptor.java:55)
	at org.databene.benerator.composite.ArrayElementTypeConverter.convert(ArrayElementTypeConverter.java:52)
	at org.databene.benerator.composite.ArrayElementTypeConverter.convert(ArrayElementTypeConverter.java:39)
	at org.databene.benerator.wrapper.ConvertingGenerator.generate(ConvertingGenerator.java:86)
	at org.databene.benerator.composite.VariableAwareGenerator.generate(VariableAwareGenerator.java:92)
	at org.databene.feed4testng.FeedIterator.fetchNext(FeedIterator.java:64)
	at org.databene.feed4testng.FeedIterator.<init>(FeedIterator.java:42)
	at org.databene.feed4testng.FeedTest.feeder(FeedTest.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:155)
	... 20 more
]]>
    </error>
  </testcase> <!-- testQuery_feed_1 -->
</testsuite> <!-- cn.nhsoft.amazoncloud.apitest.positem.PosItemTest1 -->
